version: '3.7'
services:
  portfolio-client:
    build:
      context: ./
      dockerfile: dockerfile
    image: michaelmason1998/portfolio_client
    container_name: Portfolio-App-Client
    ports:
      - "6005:6005"
    networks:
      - app-network
networks:
  app-network:
    external: true