version: '3.3'
services:
  portfolio-client:
    build:
      context: ./
      dockerfile: dockerfile
    image: michaelmason1998/portfolio_client
    container_name: Portfolio-App-Client
    ports:
      - "5000:5000"
    networks:
      - app-network
    restart: unless-stopped
networks:
  app-network:
    external: true